server.port: 8080
spring.profiles.active: local

management.endpoints.web.exposure.include: '*'

app.client:
  backend:
    baseUrl: http://localhost:8081/tickets

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: TRACE
