server.port: 8080

app.client:
  backend:
    baseUrl: http://localhost:8081/tickets

spring.security.oauth2.client:
  # https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html#oauth2login-boot-property-mappings
  # https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html#oauth2Client-client-registration
  registration:
    keycloak:
      client-id: demo-client-auth-code
      client-secret: fe5f8402-cb20-40e4-988f-43239c55095f
      scope: 'openid, profile, roles'
      authorization-grant-type: authorization_code
      redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  provider:
    keycloak:
      issuerUri: http://localhost:9000/auth/realms/demo # keycloak needs to be up and running
      authorization-uri: http://localhost:9000/auth/realms/demo/protocol/openid-connect/auth
      token-uri: http://localhost:9000/auth/realms/demo/protocol/openid-connect/token
      jwk-set-uri: http://localhost:9000/auth/realms/demo/protocol/openid-connect/certs
      user-info-uri: http://localhost:9000/auth/realms/demo/protocol/openid-connect/userinfo
      user-name-attribute: preferred_username
