server.port: 8080

app.client:
  backend:
    baseUrl: http://backend:8080/tickets

spring.security.oauth2.client:
  registration:
    keycloak:
      redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  provider:
    keycloak:
      authorization-uri: http://localhost:9000/auth/realms/demo/protocol/openid-connect/auth
      token-uri: http://keycloak:8080/auth/realms/demo/protocol/openid-connect/token
      jwk-set-uri: http://keycloak:8080/auth/realms/demo/protocol/openid-connect/certs
      user-info-uri: http://keycloak:8080/auth/realms/demo/protocol/openid-connect/userinfo
